import { motion } from "framer-motion";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { EmailRecord } from "../lib/api";

const ActivityChart = ({ emails }: { emails: EmailRecord[] }) => {
	const data = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const next = new Date(date); next.setDate(next.getDate() + 1); const dayEmails = emails.filter((email) => new Date(email.createdAt) >= date && new Date(email.createdAt) < next); return { day: date.toLocaleDateString([], { weekday: "short" }), sent: dayEmails.filter((email) => email.status === "SENT").length, scheduled: dayEmails.filter((email) => email.status === "SCHEDULED").length, failed: dayEmails.filter((email) => email.status === "FAILED").length }; });
	return <motion.section className="surface-card min-w-0 p-5 sm:p-6" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1 }}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="section-label">Performance</p><h2 className="mt-1 text-base font-bold text-white">Email activity</h2></div><div className="flex gap-4 text-[11px] text-slate-400"><span>Sent</span><span>Scheduled</span><span>Failed</span></div></div><div className="mt-6 h-[245px] w-full">{emails.length === 0 ? <p className="pt-16 text-center text-sm text-slate-500">No campaign activity yet.</p> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 8, right: 4, left: -24, bottom: 0 }}><defs><linearGradient id="dashboardSent" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#60a5fa" stopOpacity={.22} /><stop offset="100%" stopColor="#60a5fa" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#ffffff0b" vertical={false} /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: "#64748b", fontSize: 11 }} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: "#64748b", fontSize: 11 }} /><Tooltip contentStyle={{ background: "#10182b", border: "1px solid #273452", borderRadius: 10, color: "#e2e8f0", fontSize: 12 }} /><Area type="monotone" dataKey="sent" stroke="#60a5fa" fill="url(#dashboardSent)" strokeWidth={2.5} /><Area type="monotone" dataKey="scheduled" stroke="#a78bfa" fill="none" strokeWidth={2} /><Area type="monotone" dataKey="failed" stroke="#fb7185" fill="none" strokeWidth={2} /></AreaChart></ResponsiveContainer>}</div></motion.section>;
};

export default ActivityChart;
